[package]
name = "wasm-renderer"
version = "0.1.0"
edition = "2021"

[build]
incremental = true

[dependencies]

iced = { version = "0.9", features = ["tokio", "image"] }
iced_native = "0.9"
wasmer = "3.2"
